package controllers

import (
	"encoding/json"
	"fmt"
	"net/http"
	"strings"
	"sync"
)

const BATCH_SIZE = 100

type Song struct {
	Title     string
	Artist    string
	Link      string
	RawLyrics []string
	Lines     []*Line
}

type Line struct {
	Song    *Song
	Value   string
	Matches []*Line
}

func Init() {
	var count int
	for _, song := range Songs {
		count += len(song.RawLyrics)
	}

	getMatches := func(wg *sync.WaitGroup, song *Song, line string) {
		defer wg.Done()

		matches, err := findLineMatches(line)
		if err != nil {
			fmt.Println(err)
			return
		}

		newLine := &Line{
			Song:    song,
			Value:   line,
			Matches: matches,
		}

		song.Lines = append(song.Lines, newLine)
	}

	var i int
	var wg sync.WaitGroup
	for _, song := range Songs {
		for _, line := range song.RawLyrics {
			wg.Add(1)
			go getMatches(&wg, song, line)
			i++

			if i%BATCH_SIZE == 0 {
				fmt.Printf("Waiting for batch to complete (%d/%d) \n", i, count)
				wg.Wait()
			}
		}
	}

	fmt.Printf("Waiting for batch to complete (%d/%d) \n", i, count)
	wg.Wait()

	fmt.Println("Done")
}

func findLineMatches(currentLine string) ([]*Line, error) {
	rhymes, err := getRhymes(getLastWord(currentLine))
	if err != nil {
		return nil, err
	}

	matches := []*Line{}
	for _, song := range Songs {
		for _, line := range song.Lines {
			lastWord := strings.ToLower(getLastWord(line.Value))

			for _, word := range rhymes {
				if strings.ToLower(word.Value) == lastWord {
					matches = append(matches, line)
				}
			}
		}
	}

	return matches, nil
}

type Word struct {
	Value string `json:"Word"`
	Score int
}

func getLastWord(line string) string {
	split := strings.Split(line, " ")
	return split[len(split)-1]
}

func getRhymes(word string) ([]Word, error) {
	url := fmt.Sprintf("http://rhymebrain.com/talk?function=getRhymes&word=%s", word)

	r, err := http.Get(url)
	if err != nil {
		return nil, err
	}
	defer r.Body.Close()

	var words []Word
	if err := json.NewDecoder(r.Body).Decode(&words); err != nil {
		return nil, err
	}

	// 300 is perfect match
	for i := 0; i < len(words); i++ {
		if words[i].Score < 250 {
			words = append(words[:i], words[i+1:]...)
			i--
		}
	}

	return words, nil
}

var Songs = []*Song{
	{
		Title:  "Nuthing but a G Thang",
		Artist: "Dr. DRE feat. Snoop Dogg",
		Link:   "http://genius.com/Dr-dre-nuthin-but-a-g-thang-lyrics",
		Lines:  []*Line{},
		RawLyrics: []string{
			"One, two, three and to the four",
			"Snoop Doggy Dogg and Dr. Dre is at the door",
			"Ready to make an entrance, so back on up",
			"Cause you know we 'bout had to rip shit up",
			"Gimme the microphone first, so I can bust like a bubble",
			"Compton and Long Beach together, now you know you in trouble",
			"Ain't nothin' but a G thang, baby",
			"Two loc'ed out G's so we're crazy",
			"Death Row is the label that pays me",
			"Unfadable, so please don't try to fade this",
			"But, uh, back to the lecture at hand",
			"Perfection is perfected, so I'm 'a let 'em understand",
			"From a young G's perspective",
			"And before me dig out a bitch I have ta' find a contraceptive",
			"You never know she could be earnin' her man",
			"And learnin' her man, and at the same time burnin' her man",
			"Now you know I ain't wit that shit, Lieutenant",
			"Ain't no pussy good enough to get burnt while I'm up in it",
			"(yeah) And that's realer than real-deal Holyfield",
			"And now you hookas and ho's know how I feel",
			"Well if it's good enough to get broke off a proper chunk",
			"I'll take a small piece of some of that funky stuff",
			"Well I'm peepin', and I'm creepin', and I'm creeping",
			"But I damn near got caught, 'cause my beeper kept beeping",
			"Now it's time for me to make my impression felt",
			"So sit back, relax, and strap on your seat belt",
			"You never been on a ride like this before",
			"With a producer who can rap and control the maestro",
			"At the same time with the dope rhyme that I kick",
			"You know, and I know, I flow some ol' funky shit",
			"To add to my collection, the selection",
			"Symbolizes dope, take a toke, but don't choke",
			"If ya' do, ya' have no clue",
			"O' what me and my homey Snoop Dogg came to do",
			"Fallin' back on that ass with a hellified gangsta' lean",
			"Gettin' funky on the mic like a' old batch o' collard greens",
			"It's the capital S, oh yes, the fresh N-double O-P",
			"D-O-double G-Y D-O-double G ya' see",
			"Showin' much flex when it's time to wreck a mic",
			"Pimpin' ho's and clockin' a grip like my name was Dolomite",
			"I think they in a mood for some motherfucking G shit",
			"So Dre. What up Dogg",
			"We gotta give 'em what they want",
			"We gotta break 'em off something",
			"And it's gotta be bumpin' City of Compton",
			"It's where it takes place so I'm a ask your attention",
			"Mobbing like a motherfucker but I ain't lynching",
			"Droppin' the funky shit that's making the sucker niggas mumble",
			"When I'm on the mic, it's like a cookie, they all crumble",
			"Try to get close, and your ass'll get smacked",
			"My motherfucking homie Doggy Dogg has my back",
			"Never let me slip, 'cause if I slip, then I'm slipping",
			"But if I got my Nina, then you know I'm straight tripping",
			"And I'm a continue to put the rap down, put the mack down",
			"And if your bitches talk shit, I have ta' put the smack down",
			"Yeah, and ya' don't stop",
			"I told you I'm just like a clock when I tick and I tock",
			"But I'm never off, always on, 'til the break dawn",
			"C-O-M-P-T-O-N, and the city they call Long Beach",
			"Puttin' the shit together",
			"Like my nigga D.O.C., no one can do it better",
		},
	},
	{
		Title:  "Juicy",
		Artist: "The Notorious B.I.G.",
		Link:   "http://genius.com/The-notorious-big-juicy-lyrics",
		Lines:  []*Line{},
		RawLyrics: []string{
			"It was all a dream, I used to read Word Up magazine",
			"Salt-n-Pepa and Heavy D up in the limousine",
			"Hangin' pictures on my wall",
			"Every Saturday Rap Attack, Mr. Magic, Marley Marl",
			"I let my tape rock 'til my tape popped",
			"Smoking weed on Bambu, sippin' on Private Stock",
			"Way back, when I had the red and black lumberjack",
			"With the hat to match",
			"Remember Rappin Duke? Duh-ha, duh-ha",
			"You never thought that hip hop would take it this far",
			"Now I'm in the limelight cause I rhyme tight",
			"Time to get paid, blow up like the World Trade",
			"Born sinner, the opposite of a winner",
			"Remember when I used to eat sardines for dinner",
			"Peace to Ron G, Brucey B, Kid Capri",
			"Funkmaster Flex, Lovebug Starski",
			"I'm blowing up like you thought I would",
			"Call the crib, same number, same hood, that's right",
			"It's all good, it's all good",
			"And if you don't know, now you know, nigga",
			"You know very well who you are",
			"Don't let 'em hold you down, reach for the stars",
			"You had a goal, but not that many",
			"Cause you're the only one",
			"I'll give you good and plenty",
			"I made the change from a common thief",
			"To up close and personal with Robin Leach",
			"And I'm far from cheap, I smoke skunk with my peeps all day",
			"Spread love, it's the Brooklyn way",
			"The Moet and Alizé keep me pissy, girls used to diss me",
			"Now they write letters cause they miss me",
			"I never thought it could happen, this rappin' stuff",
			"I was too used to packing gats and stuff",
			"Now honeys play me close like butter play toast",
			"From the Mississippi down to the East Coast",
			"Condos in Queens, indo for weeks",
			"Sold out seats to hear Biggie Smalls speak",
			"Living life without fear",
			"Putting 5 carats in my baby girl's ear",
			"Lunches, brunches, interviews by the pool",
			"Considered a fool cause I dropped out of high school",
			"Stereotypes of a black male misunderstood",
			"And it's still all good",
			"Uh, and if you don't know, now you know, nigga",
			"Super Nintendo, Sega Genesis",
			"When I was dead broke, man, I couldn't picture this",
			"50-inch screen, money green leather sofa",
			"Got two rides, a limousine with a chauffeur",
			"Phone bill about two G's flat",
			"No need to worry, my accountant handles that",
			"And my whole crew is lounging",
			"Celebrating every day, no more public housing",
			"Thinking back on my one-room shack",
			"Now my mom pimps a Ac with minks on her back",
			"And she loves to show me off of course",
			"Smiles every time my face is up in The Source",
			"We used to fuss when the landlord dissed us",
			"No heat, wonder why Christmas missed us",
			"Birthdays was the worst days",
			"Now we sip champagne when we thirsty",
			"Uh, damn right I like the life I live",
			"Cause I went from negative to positive",
			"And it's all good, it's all good",
			"And if you don't know, now you know, nigga",
		},
	},
	{
		Title:  "Straight Outta Compton",
		Artist: "N.W.A.",
		Link:   "http://genius.com/Nwa-straight-outta-compton-lyrics",
		Lines:  []*Line{},
		RawLyrics: []string{
			"Straight outta Compton, crazy motherfucker named Ice Cube",
			"From the gang called Niggas Wit Attitudes",
			"When I'm called off, I got a sawed-off",
			"Squeeze the trigger and bodies are hauled off",
			"You too, boy, if you fuck with me",
			"The police are gonna have to come and get me",
			"Off your ass, that's how I'm going out",
			"For the punk motherfuckers that's showing out",
			"Niggas start to mumble, they wanna rumble",
			"Mix 'em and cook 'em in a pot, like gumbo",
			"Going off on the motherfucker like that",
			"With a gat that's pointed at your ass",
			"So give it up smooth",
			"Ain't no telling when I'm down for a jack move",
			"Here's a murder rap to keep y'all dancin'",
			"With a crime record like Charles Manson",
			"AK-47 is the tool",
			"Don't make me act a motherfucking fool",
			"Me you can go toe to toe, no maybe",
			"I'm knocking niggas out the box, daily",
			"Yo, weekly, monthly and yearly",
			"Until them dumb motherfuckers see clearly",
			"That I'm down with the capital C-P-T",
			"Boy, you can't fuck with me",
			"So when I'm in your neighborhood, you better duck",
			"'Cause Ice Cube is crazy as fuck",
			"As I leave, believe I'm stompin'",
			"But when I come back boy, I'm coming straight outta Compton",
			"Straight outta Compton, another crazy ass nigga",
			"More punks I smoke, yo, my rep gets bigger",
			"I'm a bad motherfucker, and you know this",
			"But the pussy-ass niggas won't show this",
			"But I don't give a fuck, I'ma make my snaps",
			"If not from the records, from jacking or craps",
			"Just like burglary, the definition is jacking",
			"And when I'm legally armed it's called packing",
			"Shoot a motherfucker in a minute",
			"I find a good piece of pussy and go up in it",
			"So if you're at a show in the front row",
			"I'ma call you a bitch or dirty-ass ho",
			"You'll probably get mad like a bitch is supposed to",
			"But that shows me, slut, you're composed to",
			"A crazy motherfucker from the street",
			"Attitude legit, 'cause I'm tearing up shit",
			"MC Ren controls the automatic",
			"For any dumb motherfucker that starts static",
			"Not the right hand, 'cause I'm the hand itself",
			"Every time I pull an AK off the shelf",
			"The security is maximum, and that's a law",
			"R-E-N spells Ren, but I'm raw",
			"See, 'cause I'm the motherfucking villain",
			"The definition is clear, you're the witness of a killin'",
			"That's taking place without a clue",
			"And once you're on the scope, your ass is through",
			"Look, you might take it as a trip",
			"But a nigga like Ren is on a gangsta tip",
			"Straight outta Compton",
			"…Straight outta Compton",
			"Is a brother that'll smother your mother",
			"And make your sister think I love her",
			"Dangerous motherfucker raising hell",
			"And if I ever get caught, I make bail",
			"See, I don't give a fuck, that's the problem",
			"I see a motherfucking cop, I don't dodge him",
			"But I'm smart, lay low, creep a while",
			"And when I see a punk pass, I smile",
			"To me it's kinda funny, the attitude showing a nigga driving",
			"But don't know where the fuck he's going, just rolling",
			"Looking for the one they call Eazy",
			"But here's a flash, they'll never seize me",
			"Ruthless, never seen, like a shadow in the dark",
			"Except when I unload",
			"You see a spark and jump over hesitation",
			"And hear the scream of the one who got the lead penetration",
			"Feel a little gust of wind and I'm jetting",
			"But leave a memory no one'll be forgetting",
			"So what about the bitch who got shot? Fuck her",
			"You think I give a damn about a bitch? I ain't a sucker",
			"This is an autobiography of the E",
			"And if you ever fuck with me",
			"You'll get taken by a stupid dope brother who will smother",
			"Word to the motherfucker, straight outta Compton",
		},
	},
	{
		Title:  "C.R.E.A.M.",
		Artist: "Wu-Tang Clan",
		Link:   "http://genius.com/Wu-tang-clan-cream-lyrics",
		Lines:  []*Line{},
		RawLyrics: []string{
			"I grew up on the crime side, the New York Times side",
			"Staying alive was no jive",
			"Had secondhands, Mom's bounced on old man",
			"So then we moved to Shaolin land",
			"A young youth, yo, rocking the gold tooth, 'Lo goose",
			"Only way I be gettin' the G off was drug loot",
			"And let's start it like this son, rolling with this one and that one",
			"Pulling out Gats for fun",
			"But it was just a dream for the teen who was a fiend",
			"Started smoking woolas at 16",
			"And running up in gates, and doing hits for high stakes",
			"Making my way on fire escapes",
			"No question I would speed for cracks and weed",
			"The combination made my eyes bleed",
			"No question I would flow off and try to get the dough all",
			"Sticking up white boys in ball courts",
			"My life got no better, same damn 'Lo sweater",
			"Times is rough and tough like leather",
			"Figured out I went the wrong route",
			"So I got with a sick-ass clique and went all out",
			"Catching keys from across seas",
			"Rolling in MPV's every week we made forty grand",
			"Yo nigga respect mine or here go the tech nine",
			"Ch-chick-POW, move from the gate now",
			"Cash rules everything around me",
			"CREAM, get the money",
			"Dollar, dollar bill y'all",
			"It's been twenty-two long hard years of still struggling",
			"Survival got me bugging, but I'm alive on arrival",
			"I peep at the shape of the streets",
			"And stay awake to the ways of the world cause shit is deep",
			"A man with a dream with plans to make cream",
			"Which failed; I went to jail at the age of fifteen",
			"A young buck selling drugs and such who never had much",
			"Trying to get a clutch at what I could not",
			"The court played me short, now I face incarceration",
			"Pacin' - going upstate's my destination",
			"Handcuffed in the back of a bus, forty of us",
			"Life as a shorty shouldn't be so rough",
			"But as the world turned I learned life is hell",
			"Living in the world no different from a cell",
			"Every day I escape from Jakes giving chase, selling base",
			"Smoking bones in the staircase",
			"Though I don't know why I chose to smoke sess",
			"I guess that's the time when I'm not depressed",
			"But I'm still depressed and I ask what's it worth?",
			"Ready to give up so I seek the old Earth",
			"Who explained working hard may help you maintain",
			"To learn to overcome the heartaches and pain",
			"We got stickup kids, corrupt cops, and crack rocks and",
			"Stray shots, all on the block that stays hot",
			"Leave it up to me while I be living proof",
			"To kick the truth to the young Black youth",
			"But shorty's running wild, smoking sess, drinking beer",
			"And ain't trying to hear what I'm kicking in his ear",
			"Neglected for now, but yo, it gots to be accepted",
			"That what? That life is hectic",
			"Niggas got to do what they got to do",
			"To get through - know what I'm saying?",
			"Because you can't just get by no more",
			"You gotta get over - straight up and down",
		},
	},
	{
		Title:  "Big Pimpin'",
		Artist: "Jay Z",
		Link:   "http://genius.com/Jay-z-big-pimpin-lyrics",
		Lines:  []*Line{},
		RawLyrics: []string{
			"You know I thug 'em, fuck 'em, love 'em, leave them",
			"'Cause I don't fucking need them",
			"Take 'em out the hood, keep 'em looking good",
			"But I don't fucking feed them",
			"First time they fuss I'm breezin'",
			"Talking 'bout, What's the reasons?",
			"I'm a pimp in every sense of the word",
			"Bitch, better trust and believe them",
			"In the cut where I keep them",
			"'Til I need a nut, 'til I need to beat the guts",
			"Then it's beep beep and I'm pickin' them up",
			"Let 'em play with the dick in the truck",
			"Many chicks wanna put Jigga's fists in cuffs",
			"Divorce him and split his bucks",
			"Just because you got good head",
			"I'ma break bread, so you can be livin' it up",
			"Shit, I part with nothing, y'all be fronting",
			"Me give my heart to a woman?",
			"Not for nothing, never happen; I'll be forever mackin'",
			"Heart cold as assassins, I got no passion, I got no patience",
			"And I hate waitin'; ho, get your ass in and let's ride!",
			"We doing big pimpin', we spending cheese",
			"Check 'em out now, big pimping on B.L.A.D.E's",
			"We doing big pimpin' up in N.Y.C",
			"It's just that Jigga Man, Pimp C, and B-U-N B",
			"Nigga, it's the big Southern rap impresario",
			"Coming straight up out the black barrio",
			"Makes a mill' up off a sorry ho",
			"Then sit back and peep my scenario",
			"Oops, my bad, that's my scenario",
			"No, I can't fuck a scary ho",
			"Now every time, every place, everywhere we go",
			"Hoes start pointing; they say, There he go!",
			"Now these motherfuckers know we carry more",
			"Heat than a little bit; we don't pull it out over little shit",
			"And if you catch a lick when I spit",
			"Then it won't be a little hit",
			"Go read a book, you illiterate son of a bitch!",
			"And step up your vocab!",
			"Don't be surprised if your ho stab out with me",
			"And you see us coming down on yo' SLAB",
			"Living ghetto-fabulous, so mad, you just can't take it",
			"But nigga if you hatin' I",
			"Then you wait while I get your bitch butt-naked",
			"Just break it; you gotta pay like you weigh",
			"Wet with two pairs of clothes on",
			"Now get yo' ass to the back as I'm flying to the track",
			"Timbaland, let me spit my prose on",
			"Pump it up in the pro-zone",
			"That's the track that we breaking these hoes on",
			"Ain't the track that we flows on",
			"But when shit get hot, then the Glock start poppin', like ozone",
			"We keep hoes crunk, like Trigger man",
			"For real, it don't get no bigger, man",
			"Don't trip, let's flip, getting throwed on the flip",
			"Getting blowed with the motherfuckin' Jigga Man, fool!",
			"Smoking out, pouring up, keeping lean up in my cup",
			"All my car got leather and wood, in my hood we call it buck",
			"Everybody wanna ball, holla at broads at the mall",
			"If he up, watch him fall, nigga, I can't fuck with y'all",
			"If I wasn't rapping, baby, I would still be ridin' Mercedes",
			"Comin' down and sippin' daily, no record til whitey pay me",
			"Uhhh, now what y'all know 'bout them Texas boys?",
			"Coming down in candied toys, smoking weed and talking noise",
			"On the canopy, my stamina be",
			"Enough for Pamela Anderson Lee",
			"MTV jam of the week",
			"Made my money quick, then back to the streets",
			"But still sittin' on blades, sippin' that Ray",
			"Standing on the corner of my block hustlin'",
			"Still getting that cane",
			"Half what I paid slipping right through customs",
			"It'll sell by night, its egg shell white",
			"I got so many grams if the man find out",
			"It will land me in jail for life",
			"But I'm still big pimpin', spending cheese",
			"With B.U.N. B, Pimp C, and Timothy",
			"We got bitches in the back of the truck",
			"Laughing it up, Jigga Man: that's what's up",
		},
	},
	{
		Title:  "99 Problems",
		Artist: "Jay Z",
		Link:   "http://genius.com/Jay-z-99-problems-lyrics",
		Lines:  []*Line{},
		RawLyrics: []string{
			"I've got the Rap Patrol on the gat patrol",
			"Foes that wanna make sure my casket's closed",
			"Rap critics that say he's Money, Cash, Hoes",
			"I'm from the hood, stupid! What type of facts are those?",
			"If you grew up with holes in your zapatos",
			"You'd celebrate the minute you was having dough",
			"I'm like, Fuck critics! You can kiss my whole asshole",
			"If you don't like my lyrics, you can press fast forward",
			"Got beef with radio if I don't play they show",
			"They don't play my hits, well, I don't give a shit, so",
			"Rap mags try and use my black ass",
			"So advertisers can give 'em more cash for ads",
			"Fuckers, I don't know what you take me as",
			"Or understand the intelligence that Jay Z has",
			"I'm from rags to riches, niggas, I ain't dumb",
			"I got 99 problems, but a bitch ain't one; hit me!",
			"99 problems, but a bitch ain't one",
			"If you're having girl problems, I feel bad for you, son",
			"I got 99 problems, but a bitch ain't one; hit me!",
			"The year is '94, in my trunk is raw",
			"In my rearview mirror is the motherfuckin' law",
			"Got two choices, y'all: pull over the car or",
			"Bounce on the devil, put the pedal to the floor",
			"And I ain't tryin' to see no highway chase with Jake",
			"Plus I got a few dollars, I can fight the case",
			"So I pull over to the side of the road",
			"I heard, Son, do you know why I'm stopping you for?",
			"‘Cause I'm young and I'm black and my hat's real low?",
			"Do I look like a mind reader, sir? I don't know",
			"Am I under arrest or should I guess some more?",
			"Well, you was doing 55 in a 54",
			"License and registration and step out of the car",
			"Are you carrying a weapon on you? I know a lot of you are",
			"I ain't stepping out of shit, all my paper's legit",
			"Well, do you mind if I look around the car a little bit?",
			"Well, my glove compartment is locked",
			"So is the trunk in the back",
			"And I know my rights, so you gon' need a warrant for that",
			"Aren't you sharp as a tack? You some type of lawyer or something? Somebody important or something?",
			"Well, I ain't passed the bar, but I know a little bit",
			"Enough that you won't illegally search my shit",
			"Well, we'll see how smart you are when the K9 come",
			"I got 99 problems, but a bitch ain't one; hit me!",
			"Now once upon a time, not too long ago",
			"A nigga like myself had to strong-arm a ho",
			"This is not a ho in the sense of having a pussy",
			"But a pussy having no goddamn sense, try and push me",
			"I try to ignore him, talk to the Lord",
			"Pray for him, but some fools just love to perform",
			"You know the type, loud as a motorbike",
			"But wouldn't bust a grape in a fruit fight",
			"And only thing that's gon' happen is I'ma get to clappin'",
			"And he and his boys gonna be yappin' to the Captain",
			"And there I go, trapped in the Kit-Kat again",
			"Back through the system with the riff-raff again",
			"Fiends on the floor, scratchin' again",
			"Paparazzis with they cameras, snappin' em",
			"D.A. try to give a nigga shaft again",
			"Half a mil' for bail ‘cause I'm African",
			"All because this fool was harassin' them",
			"Tryin' to play the boy like he's saccharine",
			"But ain't nothing sweet 'bout how I hold my gun",
			"I got 99 problems, but a bitch ain't one; hit me!",
		},
	},
	{
		Title:  "Dear Momma",
		Artist: "2Pac",
		Link:   "http://genius.com/2pac-dear-mama-lyrics",
		Lines:  []*Line{},
		RawLyrics: []string{
			"When I was young, me and my mama had beef",
			"17 years old, kicked out on the streets",
			"Though back at the time I never thought I'd see her face",
			"Ain't a woman alive that could take my mama's place",
			"Suspended from school",
			"And scared to go home, I was a fool",
			"With the big boys breaking all the rules",
			"I shed tears with my baby sister, over the years",
			"We was poorer than the other little kids",
			"And even though we had different daddies, the same drama",
			"When things went wrong we'd blame Mama",
			"I reminisce on the stress I caused, it was hell",
			"Huggin' on my mama from a jail cell",
			"And who'd think in elementary, hey",
			"I'd see the penitentiary one day?",
			"And running from the police, that's right",
			"Mama catch me, put a whoopin' to my backside",
			"And even as a crack fiend, Mama",
			"You always was a black queen, Mama",
			"I finally understand",
			"For a woman it ain't easy trying to raise a man",
			"You always was committed",
			"A poor single mother on welfare, tell me how you did it",
			"There's no way I can pay you back, but the plan",
			"Is to show you that I understand; you are appreciated",
			"Now, ain't nobody tell us it was fair",
			"No love from my daddy, 'cause the coward wasn't there",
			"He passed away and I didn't cry, 'cause my anger",
			"Wouldn't let me feel for a stranger",
			"They say I'm wrong and I'm heartless, but all along",
			"I was looking for a father he was gone",
			"I hung around with the thugs",
			"And even though they sold drugs",
			"They showed a young brother love",
			"I moved out and started really hangin'",
			"I needed money of my own, so I started slangin'",
			"I ain't guilty, 'cause even though I sell rocks",
			"It feels good putting money in your mailbox",
			"I love paying rent when the rent is due",
			"I hope you got the diamond necklace that I sent to you",
			"'Cause when I was low you was there for me",
			"And never left me alone, because you cared for me",
			"And I could see you coming home after work late",
			"You're in the kitchen, trying to fix us a hot plate",
			"You just working with the scraps you was given",
			"And Mama made miracles every Thanksgivin'",
			"But now the road got rough, you're alone",
			"You're trying to raise two bad kids on your own",
			"And there's no way I can pay you back, but my plan",
			"Is to show you that I understand; you are appreciated",
			"Pour out some liquor and I reminisce",
			"'Cause through the drama I can always depend on my mama",
			"And when it seems that I'm hopeless",
			"You say the words that can get me back in focus",
			"When I was sick as a little kid",
			"To keep me happy, there's no limit to the things you did",
			"And all my childhood memories",
			"Are full of all the sweet things you did for me",
			"And even though I act crazy",
			"I gotta thank the Lord that you made me",
			"There are no words that can express how I feel",
			"You never kept a secret, always stayed real",
			"And I appreciate how you raised me",
			"And all the extra love that you gave me",
			"I wish I could take the pain away",
			"If you can make it through the night, there's a brighter day",
			"Everything will be alright if you hold on",
			"It's a struggle every day, gotta roll on",
			"And there's no way I can pay you back, but my plan",
			"Is to show you that I understand; you are appreciated",
		},
	},
	{
		Title:  "California Love",
		Artist: "2Pac",
		Link:   "http://genius.com/2pac-california-love-lyrics",
		Lines:  []*Line{},
		RawLyrics: []string{
			"California... knows how to party",
			"California... knows how to party",
			"In the citaaay of L.A.",
			"In the citaaay of good ol' Watts",
			"In the citaaay, the city of Compton",
			"We keep it rockin! We keep it rockin!",
			"Now let me welcome everybody to the wild, wild west",
			"A state that's untouchable like Elliot Ness",
			"The track hits ya eardrum like a slug to ya chest",
			"Pack a vest for your Jimmy in the city of sex",
			"We in that sunshine state where that bomb ass hemp be",
			"The state where ya never find a dance floor empty",
			"And pimps be on a mission for them greens",
			"Lean mean money-makin-machines servin fiends",
			"I been in the game for ten years makin rap tunes",
			"Ever since honeys was wearin sassoon",
			"Now it's '95 and they clock me and watch me",
			"Diamonds shinin lookin like I robbed Liberace",
			"It's all good, from Diego to tha Bay",
			"Your city is tha bomb if your city makin pay",
			"Throw up a finger if ya feel the same way",
			"Dre puttin it down for Californ-I-a",
			"Out on bail fresh outta jail, California dreamin",
			"Soon as I stepped on the scene, I'm hearin hoochies screamin",
			"Fiendin for money and alcohol",
			"The life of a west side playa where cowards die and it's all ball",
			"Only in Cali where we riot not rally to live and die",
			"In L.A. we wearin Chucks not Ballies (that's right)",
			"Dressed in Locs and khaki suits and ride is what we do",
			"Flossin but have caution we collide with other crews",
			"Famous cause we program worldwide",
			"Let'em recognize from Long Beach to Rosecrans",
			"Bumpin and grindin like a slow jam, it's west side",
			"So you know the row won't bow down to no man",
			"Say what you say",
			"But give me that bomb beat from Dre",
			"Let me serenade the streets of L.A.",
			"From Oakland to Sacktown",
			"The Bay Area and back down",
			"Cali is where they put they mack down",
			"Give me love!",
			"Throw it up y'all, throw it up, Throw it up",
			"Let's show these fools how we do this on that west side",
			"Cause you and I know it's tha best side",
		},
	},
	{
		Title:  "In Da Club",
		Artist: "50 Cent",
		Link:   "http://genius.com/50-cent-in-da-club-lyrics",
		Lines:  []*Line{},
		RawLyrics: []string{
			"Go shorty, it's your birthday",
			"We gonna party like it's your birthday",
			"We gonna sip Bacardi like it's your birthday",
			"And you know we don't give a fuck it's not your birthday",
			"You can find me in the club, bottle full of bub",
			"Look, mami, I got the X if you into taking drugs",
			"I'm into having sex, I ain't into making love",
			"So come give me a hug if you're into getting rubbed",
			"You can find me in the club, bottle full of bub'",
			"Look, mami, I got the X if you into taking drugs",
			"I'm into having sex, I ain't into making love",
			"So come give me a hug if you're into getting rubbed",
			"When I pull up out front you see the Benz on dubs",
			"When I roll twenty deep it's twenty knives in the club",
			"Niggas heard I fuck with Dre, now they wanna show me love",
			"When you sell like Eminem and the hoes they wanna fuck",
			"But, homie, ain't nothing changed: hoes down, G's up",
			"I see Xzibit in the cut, nigga, roll the weed up",
			"If you watch how I move you'll mistake me for a player or pimp",
			"Been hit with a few shells, but I don't walk with a limp",
			"In the hood in L.A. they saying 50, you hot",
			"They like me, I want them to love me like they love Pac",
			"But holla in New York the niggas'll tell you I'm loco",
			"And the plan is to put the rap game in a chokehold",
			"I'm fully focused, man, my money on my mind",
			"Got a mil out the deal and I'm still on the grind",
			"Now shorty said she feelin' my style, she feelin' my flow",
			"Her girlfriend willing to get bi and they ready to go",
			"My flow, my show brought me the dough",
			"That bought me all my fancy things",
			"My crib, my cars, my pools, my jewels",
			"Look, nigga, I done came up and I ain't changed",
			"And you should love it way more than you hate it",
			"Nigga, you mad? I thought that you'd be happy I made it",
			"I'm that cat by the bar toasting to the good life",
			"You the faggot ass nigga trying to pull me back, right?",
			"When my joint get to pumpin' in the club it's on",
			"I wink my eye at your bitch, if she smiles she gone",
			"If the roof on fire, let the motherfucker burn",
			"If you talking about money, homie, I ain't concerned",
			"I'ma tell you what Banks told me",
			"Cuz, go 'head, switch the style up",
			"If niggas hate then let them hate",
			"And watch the money pile up",
			"Or we can go upside your head with a bottle of bub'",
			"They know where we fucking be",
		},
	},
	{
		Title:  "Lose Yourself",
		Artist: "Eminem",
		Link:   "http://genius.com/Eminem-lose-yourself-lyrics",
		Lines:  []*Line{},
		RawLyrics: []string{
			"His palms are sweaty, knees weak, arms are heavy",
			"There's vomit on his sweater already: Mom's spaghetti",
			"He's nervous, but on the surface he looks calm and ready",
			"To drop bombs, but he keeps on forgetting",
			"What he wrote down, the whole crowd goes so loud",
			"He opens his mouth, but the words won't come out",
			"He's choking, how? Everybody's joking now",
			"The clock's run out, time's up, over – blaow!",
			"Snap back to reality, oh, there goes gravity",
			"Oh, there goes Rabbit, he choked, he's so mad but he won't",
			"Give up that easy nope, he won't have it, he knows",
			"His whole back's to these ropes, it don't matter, he's dope",
			"He knows that, but he's broke, he's so stagnant, he knows",
			"When he goes back to this mobile home, that's when it's",
			"Back to the lab again, yo! This whole rhapsody",
			"He better go capture this moment and hope it don't pass him",
			"You better lose yourself in the music, the moment",
			"You own it, you better never let it go",
			"You only get one shot, do not miss your chance to blow",
			"This opportunity comes once in a lifetime, yo",
			"You better lose yourself in the music, the moment",
			"You own it, you better never let it go",
			"You only get one shot, do not miss your chance to blow",
			"This opportunity comes once in a lifetime, yo",
			"The soul's escaping through this hole that is gaping",
			"This world is mine for the taking, make me king",
			"As we move toward a New World Order",
			"A normal life is boring; but superstardom's",
			"Close to post-mortem, it only grows harder",
			"Homie grows hotter, he blows it's all over",
			"These hoes is all on him, coast to coast shows",
			"He's known as the Globetrotter, lonely roads",
			"God only knows, he's grown farther from home, he's no father",
			"He goes home and barely knows his own daughter",
			"But hold your nose cause here goes the cold water",
			"These hoes don't want him no mo', he's cold product",
			"They moved on to the next schmoe who flows",
			"He nose-dove and sold nada, and so the soap opera",
			"Is told, it unfolds, I suppose it's old, partner",
			"But the beat goes on: da-da-dum da-dum dah-dah",
			"No more games, I'ma change what you call rage",
			"Tear this motherfuckin' roof off like two dogs caged",
			"I was playing in the beginning, the mood all changed",
			"I've been chewed up and spit out and booed off stage",
			"But I kept rhyming and stepped right in the next cypher",
			"Best believe somebody's paying the Pied Piper",
			"All the pain inside amplified by the",
			"Fact that I can't get by with my nine-to-",
			"Five and I can't provide the right type of",
			"Life for my family, cause man, these God damn",
			"Food stamps don't buy diapers, and there's no movie",
			"There's no Mekhi Phifer, this is my life",
			"And these times are so hard, and it's getting even harder",
			"Tryna feed and water my seed plus, teeter-totter",
			"Caught up between being a father and a prima donna",
			"Baby momma drama, screaming on her too much for me to wanna stay in one spot, another day of monotony",
			"Has gotten me to the point, I'm like a snail, I've got",
			"To formulate a plot, or end up in jail or shot",
			"Success is my only motherfuckin' option – failure's not",
			"Mom, I love you, but this trailer's got to go",
			"I cannot grow old in Salem's Lot",
			"So here I go, it's my shot, feet: fail me not",
			"This may be the only opportunity that I got",
		},
	},
	{
		Title:  "It Was A Good Day",
		Artist: "Ice Cube",
		Link:   "http://genius.com/Ice-cube-it-was-a-good-day-lyrics",
		Lines:  []*Line{},
		RawLyrics: []string{
			"Just wakin up in the mornin gotta thank God",
			"I don't know but today seems kinda odd",
			"No barkin from the dog, no smog",
			"And momma cooked a breakfast with no hog",
			"I got my grub on, but didn't pig out",
			"Finally got a call from a girl I wanna dig out",
			"Hooked it up for later as I hit the do'",
			"Thinkin will I live, another twenty-fo'",
			"I gotta go cause I got me a drop top",
			"And if I hit the switch, I can make the ass drop",
			"Had to stop, at a red light",
			"Lookin in my mirror and not a jacker in sight",
			"And everything is alright",
			"I got a beep from Kim, and she can fuck all night",
			"Called up the homies and I'm askin y'all",
			"Which park, are y'all playin basketball?",
			"Get me on the court and I'm trouble",
			"Last week fucked around and got a triple double",
			"Freakin niggaz everyway like M.J.",
			"I can't believe, today was a good day",
			"Drove to the pad and hit the showers",
			"Didn't even get no static from the cowards",
			"Cause just yesterday them fools tried to blast me",
			"Saw the police and they rolled right past me",
			"No flexin, didn't even look in a nigga's direction",
			"as I ran the intersection",
			"Went to $hort Dog's house, they was watchin Yo! MTV Raps",
			"What's the haps on the craps?",
			"Shake 'em up, shake 'em up, shake 'em up, shake 'em",
			"Roll 'em in a circle of niggaz and watch me break 'em",
			"with the seven, seven-eleven, seven-eleven",
			"Seven even back do' Lil' Joe",
			"I picked up the cash flow",
			"Then we played bones, and I'm yellin domino",
			"Plus nobody I know got killed in South Central L.A.",
			"Today was a good day",
			"Left my nigga's house paid",
			"Picked up a girl been tryin to fuck since the 12th grade",
			"It's ironic, I had the brew she had the chronic",
			"The Lakers beat the Supersonics",
			"I felt on the big fat fanny",
			"Pulled out the jammy, and killed the punanny",
			"And my dick runs deep, so deep",
			"So deep put her ass to sleep",
			"Woke her up around one",
			"She didn't hesitate, to call Ice Cube the top gun",
			"Drove her to the pad and I'm coastin",
			"Took another sip of the potion hit the three-wheel motion",
			"I was glad everything had worked out",
			"Dropped her ass off and then chirped out",
			"Today was like one of those fly dreams",
			"Didn't even see a berry flashin those high beams",
			"No helicopter looking for a murder",
			"Two in the mornin got the Fatburger",
			"Even saw the lights of the Goodyear Blimp",
			"And it read, Ice Cube's a pimp",
			"Drunk as hell but no throwin up",
			"Half way home and my pager still blowin up",
			"Today I didn't even have to use my A.K.",
			"I got to say it was a good day",
			"Hey wait, wait a minute Pooh, stop this shit",
			"What the fuck I'm thinkin about?",
		},
	},
	{
		Title:  "The World is Yours",
		Artist: "Nas",
		Link:   "http://genius.com/Nas-the-world-is-yours-lyrics",
		Lines:  []*Line{},
		RawLyrics: []string{
			"Whose world is this?",
			"The world is yours, the world is yours",
			"It's mine, it's mine, it's mine; whose world is this?",
			"It's mine, it's mine, it's mine; whose world is this?",
			"The world is yours, the world is yours",
			"It's mine, it's mine, it's mine; whose world is this?",
			"I sip the Dom P, watching Gandhi 'til I'm charged",
			"Then writing in my book of rhymes",
			"All the words past the margin",
			"Behold the mic I'm throbbin', mechanical movement",
			"Understandable smooth shit that murderers move with",
			"The thief's theme; play me at night, they won't act right",
			"The fiend of hip-hop has got me stuck like a crack pipe",
			"The mind activation, react like I'm facin'",
			"Time like Pappy Mason, with pens I'm embracin'",
			"Wipe the sweat off my dome, spit the phlegm on the streets",
			"Suede Timbs on my feet makes my cipher complete",
			"Whether cruising in a Six cab or Montero Jeep",
			"I can't call it; the beats make me falling asleep",
			"I keep falling, but never falling six feet deep",
			"I'm out for presidents to represent me (say what?)",
			"I'm out for dead presidents to represent me",
			"To my man Ill Will, God bless your life",
			"To my peoples throughout Queens, God bless your life",
			"I trip, we box up crazy bitches",
			"Aimin' guns in all my baby pictures",
			"Beef with housing police",
			"Release scriptures that's maybe Hitler's",
			"Yet I'm the mild, money-gettin' style, rollin' foul",
			"The versatile, honey-sticking, wild golden child",
			"Dwelling in the Rotten Apple, you get tackled",
			"Or caught by the devil's lasso, shit is a hassle",
			"There's no days for broke days we sell it; smoke pays",
			"While all the old folks pray to Jesús",
			"Soakin' their sins in trays of holy water",
			"Odds against Nas are slaughter",
			"Thinking a word best describing my life to name my daughter",
			"My strength, my son, the star will be my resurrection",
			"Born in correction, all the wrong shit I did",
			"He'll lead a right direction",
			"How you living? Large, a broker charge, cards are mediocre",
			"You flippin' coke or playin' spit, spades, and strip poker?",
			"I'm the young city bandit, hold myself down single-handed",
			"For murder raps, I kick my thoughts alone, get remanded",
			"Born alone, die alone; no crew to keep my crown or throne",
			"I'm deep by sound alone",
			"Caved inside, 1,000 miles from home",
			"I need a new nigga for this black cloud to follow",
			"‘Cause while it's over me it's too dark to see tomorrow",
			"Tryin' to maintain, I flip, fill the clip to the tip",
			"Picturing my peeps not eating can make my heartbeat skip",
			"And I'm amped up, they locked the champ up",
			"Even my brain's in handcuffs",
			"Headed for Indiana, stabbing women like the Phantom",
			"The crew is lampin' Big Willie style",
			"Check the chip-toothed smile, plus I profile wild",
			"Stash loot in fly clothes, burning dollars to light my stoge",
			"Walk the blocks with a bop",
			"Checkin' dames, plus the games people play bust the problems of the world today",
		},
	},
	{
		Title:  "Buggin' Out",
		Artist: "A Tribe Called Quest",
		Link:   "http://genius.com/A-tribe-called-quest-buggin-out-lyrics",
		Lines:  []*Line{},
		RawLyrics: []string{
			"Yo, microphone check one, two, what is this?",
			"The five foot assassin with the roughneck business",
			"I float like gravity, never had a cavity",
			"Got more rhymes than the Winans got family",
			"No need to sweat Arsenio to gain some type of fame",
			"No shame in my game cause I'll always be the same",
			"Styles upon styles upon styles is what I have",
			"You wanna diss the Phifer but you still don't know the half",
			"I sport New Balance sneakers to avoid a narrow path",
			"Mess around with this you catch a size eight up your {ass}",
			"I never half step cause I'm not a half stepper",
			"Drink a lot of soda so they call me Dr. Pepper",
			"Refuse to compete with BS competition",
			"Your name ain't Special Ed so won't you seckle with the mission",
			"I never walk the street thinking it's all about me",
			"Even though deep in my heart, it really could be",
			"I just try my best to like go all out",
			"Some might even say yo shorty black you're buggin' out",
			"Zulu Nation, brothers last creation",
			"Minds get flooded, ejaculation",
			"Right on the two inch tape",
			"The Abstract poet incognito, runs the cape",
			"Not the best not the worst and occasionally I curse",
			"To get my point across, so bust, the floss",
			"As I go in between, the grit and the dirt",
			"Listen to the mission listen Miss as I do work, umm",
			"As I crack the, monotone",
			"Children of the jazz so, get your own",
			"Smokin R&B cause they try to do me",
			"Or the best of the pack but they can't do rap",
			"For it's Abstract, original",
			"You can't get your own and that's, pitiful",
			"I know I'd be the man if I cold yanked the plug",
			"On R&B, but I can't and that's bugged",
			"Yo when you bug out, you usually have a reason for the action",
			"Sometimes you do it just for mere satisfaction",
			"People be hounding, always surrounding",
			"Pulsing, just like a migraine pounding",
			"You don't really fret, you stay in your sense",
			"Camouflage your feeling, of absolute tense",
			"You soar off to another world, deep in your mind",
			"But people seem to take that, as being unkind",
			"Oh yo he's acting stank, really on a regal?",
			"A man of the fame not a man of the people",
			"Believe that if you wanna but I tell you this much",
			"Riding on the train with no dough, sucks",
			"Once again a case of your feet in my Nike's",
			"If a crowd is in my realm I'm saying -- mic please",
			"Hip-hop is living, can't yank the plug",
			"If you do the result, will end up kind of bugged",
			"Yo, I am not an invalid although I used to smoke the weed out",
			"Ali Shaheed Muhammad used to say I had to be out",
			"Scheming on the cookies with the crazy booming back buns",
			"Pushing on them real hard just so we can have the big fun",
			"When I left for Rosie I was Boulevard status",
			"Battling a MC was when Tip was at his maddest",
			"It was one MC after one MC",
			"What the world could they be wanting see from little old me",
			"Do I have the formula to save the world?",
			"Or was it just because I used to swipe the women and all the girls",
			"I'm the type of brother with the crazy extended hand, kid",
			"Dissed by all my brothers I was all up what my man did",
			"Supposed to be my man but now I wonder cause you're feeble",
			"I go out with the strongies and I separate the evils",
			"It's your brain against my mind, for those about to boot out",
			"All you nasty critters even though you see I bug out",
		},
	},
}
